apiVersion: v1
kind: PersistentVolume
metadata:
  name: postgres-pv
spec:
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 10Gi
  storageClassName: local-path
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: "/mnt/data/postgres"